### ISSUE TITLE
Battlescape: CtD as building collapses and alien knocked out

### ISSUE THREAD

**Issue by FilmBoy84** [OpenApoc/OpenApoc#413]
![image](https://user-images.githubusercontent.com/33913088/47176317-34487700-d30d-11e8-880b-ffe0fc74f482.png)
![image](https://user-images.githubusercontent.com/33913088/47176328-3a3e5800-d30d-11e8-9faf-5db02576205f.png)
![image](https://user-images.githubusercontent.com/33913088/47176333-3dd1df00-d30d-11e8-9fc8-d0770c69f714.png)

**Comment by FranciscoDA** [comment]
I had a similar issue. Stack trace below:
```
#0  OpenApoc::BattleMapPart::updateFalling (this=<optimized out>, state=..., ticks=<optimized out>)
    at /home/francisco/OpenApoc/game/state/tilemap/tileobject.h:46
#1  0x000055dc901d3c1d in OpenApoc::BattleMapPart::update (this=0x7f7a34126b40, state=..., ticks=ticks@entry=2)
    at /home/francisco/OpenApoc/game/state/battle/battlemappart.cpp:1124
#2  0x000055dc901a0c5f in OpenApoc::Battle::update (this=0x7f7a3400f000, state=..., ticks=ticks@entry=2)
    at /usr/include/c++/8.2.1/bits/shared_ptr_base.h:998
#3  0x000055dc902d0223 in OpenApoc::GameState::update (this=0x55dc928089c0, ticks=ticks@entry=2)
    at /usr/include/c++/8.2.1/bits/shared_ptr_base.h:998
#4  0x000055dc9000f478 in OpenApoc::BattleView::update (this=0x55dc92dcd440) at /usr/include/c++/8.2.1/bits/shared_ptr_base.h:998
#5  0x000055dc8ff29952 in OpenApoc::Framework::run (this=this@entry=0x55dc92279c70, 
    initialStage=std::shared_ptr<OpenApoc::Stage> (use count 1, weak count 1) = {...}) at /usr/include/c++/8.2.1/bits/shared_ptr_base.h:998
#6  0x000055dc8ff0144e in main (argc=<optimized out>, argv=0x7ffe9cdd1368) at /usr/include/c++/8.2.1/bits/shared_ptr_base.h:734
```
