### ISSUE TITLE
Crash after losing base assault

### ISSUE THREAD

**Issue by JonnyH** [OpenApoc/OpenApoc#915]
Crash after failing base assault. Backtrace:

#7  0x0000555555a7246a in OpenApoc::Base::die (this=0x7fff211892f0, state=..., collapse=false)                                                       
    at /home/jonny/code/projects/OpenApoc/game/state/city/base.cpp:122                                                                                        
#8  0x00005555559c0356 in OpenApoc::Battle::exitBattle (state=...) at /home/jonny/code/projects/OpenApoc/game/state/battle/battle.cpp:3417
#9  0x000055555589c87f in operator() (__closure=0x555558f8b390) at /home/jonny/code/projects/OpenApoc/game/ui/battle/battledebriefing.cpp:23         
#10 0x000055555589e4a2 in std::__invoke_impl<void, OpenApoc::BattleDebriefing::BattleDebriefing(OpenApoc::sp<OpenApoc::GameState>)::<lambda(OpenApoc::Event*)>
&, OpenApoc::FormsEvent*>(std::__invoke_other, struct {...} &) (__f=...) at /usr/include/c++/10.1.0/bits/invoke.h:60
#11 0x000055555589e374 in std::__invoke_r<void, OpenApoc::BattleDebriefing::BattleDebriefing(OpenApoc::sp<OpenApoc::GameState>)::<lambda(OpenApoc::Event*)>&, 
OpenApoc::FormsEvent*>(struct {...} &) (__fn=...) at /usr/include/c++/10.1.0/bits/invoke.h:110
#12 0x000055555589e16a in std::_Function_handler<void(OpenApoc::FormsEvent*), OpenApoc::BattleDebriefing::BattleDebriefing(OpenApoc::sp<OpenApoc::GameState>):
:<lambda(OpenApoc::Event*)> >::_M_invoke(const std::_Any_data &, OpenApoc::FormsEvent *&&) (__functor=..., __args#0=@0x7fffffffded0: 0x555557d59490)
    at /usr/include/c++/10.1.0/bits/std_function.h:291
#13 0x00005555556d8319 in std::function<void (OpenApoc::FormsEvent*)>::operator()(OpenApoc::FormsEvent*) const (this=0x555558f8b390, __args#0=0x555557d59490)
    at /usr/include/c++/10.1.0/bits/std_function.h:622
#14 0x00005555556d4617 in OpenApoc::Control::triggerEventCallbacks (this=0x555558a93ea0, e=0x555557d59490)
    at /home/jonny/code/projects/OpenApoc/forms/control.cpp:1163                                                                                              
#15 0x00005555556d43f7 in OpenApoc::Control::pushFormEvent (this=0x555558a93ea0, type=OpenApoc::FormEventType::ButtonClick, parentEvent=0x555557dac220)
    at /home/jonny/code/projects/OpenApoc/forms/control.cpp:1156
#16 0x00005555556ebe91 in OpenApoc::GraphicButton::eventOccured (this=0x555558a93ea0, e=0x555557dac220)
    at /home/jonny/code/projects/OpenApoc/forms/graphicbutton.cpp:54
#17 0x00005555556cdaef in OpenApoc::Control::eventOccured (this=0x555557424890, e=0x555557dac220) at /home/jonny/code/projects/OpenApoc/forms/control.cpp:108
#18 0x00005555556ea01d in OpenApoc::Form::eventOccured (this=0x555557424890, e=0x555557dac220) at /home/jonny/code/projects/OpenApoc/forms/form.cpp:34
#19 0x000055555589d8b4 in OpenApoc::BattleDebriefing::eventOccurred (this=0x7fff1db4c790, e=0x555557dac220)
    at /home/jonny/code/projects/OpenApoc/game/ui/battle/battledebriefing.cpp:63
#20 0x00005555555dec4d in OpenApoc::Framework::processEvents (this=0x555556468360) at /home/jonny/code/projects/OpenApoc/framework/framework.cpp:610
#21 0x00005555555dd193 in OpenApoc::Framework::run (this=0x555556468360, initialStage=std::shared_ptr<OpenApoc::Stage> (use count 1, weak count 1) = {...})
    at /home/jonny/code/projects/OpenApoc/framework/framework.cpp:458

Repro steps:
- Get attacked in a base
- Get some of your agents out by running out the access lift
- Lose the mission

The 
`for (auto a : building->currentAgents)
	{
		auto agent = a;
		agent->die(state, true);
	}`
snippet isn't correct, as Agent::die() removes the agent from the building->currentAgents, invalidating the current iterator.

Note that just below this the same construct is used for building->currentVehicles, which likely has the same issue.

**Comment by FilmBoy84** [comment]
Fixed in #1627
